Add or edit ingredient in recipe
adaits-2daw-cliente-grupo1/ejercicio-1 pull request #36
Opened 2017-11-02 23:02 UTC by Juanlu1995

2017-11-03 08:14 UTC, MeLlamoPablo requested changes

2017-11-03 08:14 UTC, MeLlamoPablo commented on src/js/pages/edit/addOrEditIngredientInRecipe.js
> +	if (typeof existingIngredientIndex !== typeof 1 || existingIngredientIndex !== undefined) {
Si `existingIngredientIndex` es `undefined` esto sigue lanzando error. Esto mismo te pasaba en la función de añadir pasos, pero lo he arreglado yo para que pasara los tests.

2017-11-03 08:14 UTC, MeLlamoPablo commented on src/js/pages/edit/addOrEditIngredientInRecipe.js
> +	const newRecipe = recipe;
Al igual que en la función de editar pasos, aquí hay que crear una copia de Recipe, y también una copia de sus arrays (si no, se copia Recipe pero sus arrays siguen siendo referencias a los arrays del original).

Fíjate en cómo lo he hecho en la otra función.

2017-11-03 16:01 UTC, MeLlamoPablo commented
@Juanlu1995 te falta la condición `typeof existingIngredientIndex !== typeof 1 || existingIngredientIndex !== undefined`

2017-11-16 01:51 UTC, Juanlu1995 commented on src/js/pages/edit/addOrEditIngredientInRecipe.js
> +	if (typeof existingIngredientIndex !== typeof 1 || existingIngredientIndex !== undefined) {
No entiendo esto @MeLlamoPablo

2017-11-19 20:20 UTC, MeLlamoPablo commented on src/js/pages/edit/addOrEditIngredientInRecipe.js
> +	if (typeof existingIngredientIndex !== typeof 1 || existingIngredientIndex !== undefined) {
Perdona que haya tardado en responderte, no me había llegado notificación. Imagina que `existingIngrdientIndex` es `undefined`:

```js
(
    typeof existingIngredientIndex /* undefined */ !== typeof 1 /* number */ || // true
    existingIngredientIndex /*undefined */ !== undefined // false
) // false || true ---> true
```

Queremos lanzar un error cuando:

* `existingIngredientIndex` **no** sea un número, **y**
* `existingIngredientIndex` **no** sea un undefined

La clave está en `y` en vez de `o`.

2017-11-19 20:26 UTC, Juanlu1995 commented on src/js/pages/edit/addOrEditIngredientInRecipe.js
> +	if (typeof existingIngredientIndex !== typeof 1 || existingIngredientIndex !== undefined) {
ah joder, vale ya

2017-11-19 20:27 UTC, Juanlu1995 commented on src/js/pages/edit/addOrEditIngredientInRecipe.js
> +	if (typeof existingIngredientIndex !== typeof 1 || existingIngredientIndex !== undefined) {
ah joder, vale, ya

2017-11-20 09:59 UTC, Juanlu1995 commented
When you want @MeLlamoPablo

2017-11-29 18:00 UTC, MeLlamoPablo approved these changes
👌

2017-11-29 18:00 UTC, merged