Get highest rated recipes
adaits-2daw-cliente-grupo1/ejercicio-1 pull request #38
Opened 2017-11-03 00:27 UTC by Juanlu1995

Función terminada a falta de ser probada. 
Faltan test. 
Close #35

2017-11-16 01:53 UTC, Juanlu1995 commented
@MeLlamoPablo Cuando quiera le echas un ojo, no recuerdo si le faltaba algo y si le faltaba tampoco encuentro el qué

2017-11-19 20:41 UTC, MeLlamoPablo requested changes
Perdona que haya tardado tanto, no me han venido notificaciones...

2017-11-19 20:41 UTC, MeLlamoPablo commented on src/js/model/Recipe.js
> +	getRating() {
Lamento decirte que esto no se puede hacer, porque es una dependencia circular. En java (creo) que sí se puede, pero node lleva este tema regular. Lo que está pasando es esto:

```js
// Recipe.js
const { getState } = require("../appState");

// appState.js
const Recipe = require("./model/Recipe");
```

Uno depende del otro, y el otro depende del uno. Y debido a cómo funciona node esto da problemas. Si quieres investigar más, [te dejo esta discusión](https://stackoverflow.com/questions/10869276/how-to-deal-with-cyclic-dependencies-in-node-js), pero por lo pronto lo más fácil es mover la función `getRating()` (que por cierto debería llamarse `getRatings` con s) fuera de `Recipe.js`.

Por ejemplo, a un archivo dentro de la carpeta `support` (que es una carpeta con funciones sueltas que son útiles) llamado `getRecipeRatings()`. En esa función le pasarías una receta y te devolvería sus ratings. La implementación sería la misma, remplazando `this` por el parámetro.

2017-11-19 20:41 UTC, MeLlamoPablo commented on src/js/pages/manage/getHighestRatedRecipes.js
> +	const RECETAS = getState.recipes();
Me imagino que habrás querido poner `getState().recipes`

2017-11-19 20:41 UTC, MeLlamoPablo commented on src/js/model/Recipe.js
> +		return RATINGS.find(x => x.idRecipe === this.idRecipe).score;
Una receta puede tener múltiples ratings. Aquí solo estás considerando el primero.

2017-11-19 20:41 UTC, MeLlamoPablo commented on src/js/pages/manage/getHighestRatedRecipes.js
> +function getHighestRatedRecipes() {
No me queda claro qué es lo que pretendes hacer (y no me funciona la función para averiguarlo, me devuelve siempre un array vacío).

Por lo que veo parece que quieres devolver un array de recetas, pero para una función así, ¿no tendría más sentido un array de objetos del tipo `{ typeOfFood, recipes }`? Un ejemplo de cómo sería:

```js
[
    {
        typeOfFood: "Mexicana",
        recipes: [ ... ]
    },
    {
        typeOfFood: "China",
        recipes: [ ... ]
    },
    {
        typeOfFood: "Española",
        recipes: [ ... ]
    }
]
```

El controlador de la función tendría que organizar los resultados por tipo, así que de esa forma sería mucho más fácil para él. De la forma en la que lo estabas haciendo es factible, pero el coste de la simplicidad de la función lo pagas en un controlador mucho más complejo.

2017-12-07 00:42 UTC, closed without merging