Function3.a
adaits-2daw-cliente-grupo1/ejercicio-1 pull request #64
Opened 2017-11-28 20:09 UTC by Juanlu1995

closes #55

2017-11-29 18:28 UTC, MeLlamoPablo commented
Buenas Juanlu, tu función no es correcta. Te he subido un tests para que lo compruebes (para que después digais que los tests no son importantes... jajaja).

[Aquí](https://travis-ci.org/adaits-2daw-cliente-grupo1/ejercicio-1/builds/309116411#L1141) es donde falla exactamente el test.

La PR se puede mergear cuando el test pase.

2017-11-29 19:51 UTC, MeLlamoPablo requested changes

2017-11-29 19:51 UTC, MeLlamoPablo commented on .idea/codeStyleSettings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Quita este archivo y all good

2017-11-29 20:18 UTC, Juanlu1995 commented on .gitignore
> +# CdeStykeSettings
esto no lo he escrito yo, pero es un comment, así que... bah

2017-12-02 16:44 UTC, MeLlamoPablo approved these changes

2017-12-02 16:44 UTC, merged